title: WoW Modding Docs
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: wotlkdev/wiki

# Theme settings:
#site_author: Carlos Pereira Atencio
repo_url: "https://github.com/wotlkdev/wiki"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
